DROP TABLE IF EXISTS Session;
DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS Role;

CREATE TABLE Role (
    Id INT PRIMARY KEY AUTO_INCREMENT,
    Created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Name VARCHAR(255) NOT NULL,
    Description VARCHAR(255) NOT NULL
);

CREATE TABLE User (
    Id INT PRIMARY KEY AUTO_INCREMENT,
    Created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UserId CHAR(32) NOT NULL,
    Username VARCHAR(255) NOT NULL,
    Password BINARY(60) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    FirstName VARCHAR(255),
    LastName VARCHAR(255),
    RoleId INT,
    FOREIGN KEY (RoleId) REFERENCES Role(Id),
    Enabled BOOLEAN DEFAULT TRUE
);

CREATE TABLE Session (
    Id INT PRIMARY KEY AUTO_INCREMENT,
    UserId INT NOT NULL,
    FOREIGN KEY (UserId) REFERENCES User(Id),
    SessionId CHAR(32) NOT NULL,
    SessionToken BINARY(60) NOT NULL,
    Expiry TIMESTAMP NOT NULL,
    Created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE UserInvitation (
    Id INT PRIMARY KEY AUTO_INCREMENT,
    Created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Username VARCHAR(255),
    Email VARCHAR(255) NOT NULL,
    FirstName VARCHAR(255),
    LastName VARCHAR(255),
    RoleId INT,
    FOREIGN KEY (RoleId) REFERENCES Role(Id)
);